services:
  backend:
    build: ./backend
    container_name: segpreg-backend
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 1234
      DB_NAME: monitoreoestudiantesbd
      DB_PORT: 3306
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks: [red_privada]
 
  frontend:
    build: ./frontend
    container_name: segpreg-frontend
    environment:
      REACT_APP_API_URL: "http://localhost:8000/"
    depends_on: [backend]
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    networks: [red_privada]

  db:
    image: mysql:8.0
    container_name: segpreg-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: monitoreoestudiantesbd
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d
    networks:
      - red_privada
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p1234"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db_data:

networks:
  red_privada:
    driver: bridge