services:
  backend:
    build: ./backend
    container_name: monitoreo-backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=monitoreoestudiantesbd
  frontend:
    build: ./frontend
    environment:
      - REACT_APP_API_URL=http://backend:8000/
    container_name: monitoreo-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
  
  db:
    image: mysql:8.0
    container_name: monitoreo-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: monitoreoestudiantesbd
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p1234"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db_data:
